import { ArrowDown, ArrowUp, ArrowUpDown, Search } from 'lucide-react';
import type { Player, PlayerMatchStatistics } from '../types/domain';
import { DataQualityBadge, EmptyState } from './Core';
import { Metric } from './ComparisonTable';

export type PlayerSortKey = 'name'|'position'|'minutes'|'goals'|'assists'|'shots'|'shotsOnTarget'|'xG'|'cards';
export interface PlayerTableProps { players: Player[]; statistics: PlayerMatchStatistics[]; query: string; onQueryChange: (query:string)=>void; sort: { key: PlayerSortKey; direction:'asc'|'desc' }; onSort:(key:PlayerSortKey)=>void; }
export function PlayerTable({ players, statistics, query, onQueryChange, sort, onSort }: PlayerTableProps) {
  const stats = new Map(statistics.map(x => [x.playerId,x]));
  const columns: { key:PlayerSortKey; label:string }[]=[{key:'name',label:'Spiller'},{key:'position',label:'Pos.'},{key:'minutes',label:'Min.'},{key:'goals',label:'Mål'},{key:'assists',label:'Assist'},{key:'shots',label:'Skudd'},{key:'shotsOnTarget',label:'På mål'},{key:'xG',label:'xG'},{key:'cards',label:'Kort'}];
  return <section className="panel player-panel"><header><span><small>Individnivå</small><h2>Spillerstatistikk</h2></span><label className="search-field"><Search size={15}/><span className="sr-only">Søk etter spiller</span><input type="search" value={query} onChange={e=>onQueryChange(e.target.value)} placeholder="Søk spiller …"/></label></header>{players.length ? <div className="table-shell"><table className="data-table player-table"><thead><tr>{columns.map(c=><th key={c.key}><button className="sort-button" onClick={()=>onSort(c.key)}>{c.label}{sort.key===c.key?(sort.direction==='asc'?<ArrowUp size={12}/>:<ArrowDown size={12}/>):<ArrowUpDown size={12}/>}</button></th>)}<th>Status</th><th>Kvalitet</th></tr></thead><tbody>{players.map(p=>{const s=stats.get(p.id); return <tr key={p.id}><th scope="row"><span className="player-name"><i>{p.number}</i>{p.name}</span></th><td>{p.position}</td><td><Metric value={s?.minutes}/></td><td><Metric value={s?.goals}/></td><td><Metric value={s?.assists}/></td><td><Metric value={s?.shots}/></td><td><Metric value={s?.shotsOnTarget}/></td><td><Metric value={s?.xG}/></td><td><Metric value={s?.cards}/></td><td><span className={`player-status status-${p.expectedStatus}`}>{p.expectedStatus}{p.startProbability != null && ` · ${p.startProbability}%`}</span></td><td>{s?<DataQualityBadge quality={s.metadata.quality}/>:<DataQualityBadge quality="unavailable"/>}</td></tr>})}</tbody></table></div>:<EmptyState message="Ingen spillere matcher søket eller utvalget."/>}</section>;
}
